import type { OemDocument } from './oem-documents-shared'
import { documentTitle } from './oem-documents-shared'
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!))
export function oemDocumentHtml(document:OemDocument,nonce:string) {
 const s=document.snapshot,receipt=document.document_type==='receipt',issuer=s.issuer||{},entries=s.paidEntries||[]
 const net=entries.reduce((n,e)=>n+(e.direction==='refund'?-e.amount:e.amount),0)
 const total=s.receivedTotal??net,refunded=entries.some(e=>e.direction==='refund')
 const content=receipt?`<div class="amount"><span>${refunded?'精算後の受領額（税込）':'受領金額（税込）'}</span><strong>¥${total.toLocaleString('ja-JP')}</strong></div><table><thead><tr><th>日付・名義</th><th>種類</th><th>金額</th></tr></thead><tbody>${entries.map(e=>`<tr><th>${esc(e.paidOn)}　${esc(e.payerName)}</th><td>${e.direction==='refund'?'返金':'入金'}</td><td>${e.direction==='refund'?'−':''}¥${e.amount.toLocaleString('ja-JP')}</td></tr>`).join('')}</tbody></table><p>銀行明細確認済みの入出金に基づく受領金額です。${s.settlementId?'精算記録の入金・返金を反映しています。':''}</p>`:`<p>下記のとおり納品しました。</p><table><tbody><tr><th>完成数量</th><td>${esc(s.completedQuantity)} ${esc(s.quantityUnit)}</td></tr><tr><th>完成日</th><td>${esc(s.completedOn)}</td></tr><tr><th>出荷日</th><td>${esc(s.shippedOn)}</td></tr><tr><th>配送会社</th><td>${esc(s.carrier)}</td></tr><tr><th>追跡番号</th><td>${esc(s.trackingNumber)}</td></tr></tbody></table>`
 return `<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive"><title>${documentTitle(document.document_type)} ${esc(document.document_number)}</title><style nonce="${nonce}">*{box-sizing:border-box}body{margin:0;background:#eef2f5;color:#172b3a;font:15px/1.7 "Yu Gothic",Meiryo,sans-serif}main{max-width:850px;margin:28px auto;padding:42px 48px;background:white;border:1px solid #d4dce3}h1{font-size:30px;letter-spacing:.18em;margin:0 0 12px}.top{display:flex;justify-content:space-between;gap:20px}.meta{text-align:right;font-size:13px}.customer{font-size:20px;font-weight:bold}.amount{margin:25px 0;padding:18px;border-block:3px solid #157585;display:flex;justify-content:space-between}.amount strong{font-size:28px}table{border-collapse:collapse;width:100%;margin:18px 0}th,td{border-bottom:1px solid #d8e0e6;padding:9px;text-align:left}td{text-align:right}.controls{text-align:right;max-width:850px;margin:18px auto}button{padding:10px 18px;background:#116c7c;color:white;border:0;border-radius:5px}footer{margin-top:28px;font-size:12px}@media(max-width:600px){main{margin:0;padding:24px 20px}.top{display:block}.meta{text-align:left;margin-top:12px}}@media print{body{background:white}main{border:0;margin:0;padding:0}.controls{display:none}}</style></head><body><div class="controls"><button id="print">印刷・PDF保存</button></div><main>${s.demo?'<p>【動作テスト・支払不要】架空の記録です。実取引・入金・納品の証明ではありません。</p>':''}<div class="top"><h1>${documentTitle(document.document_type)}</h1><div class="meta">番号：${esc(document.document_number)}<br>発行日：${esc(s.issuedDate)}<br>注文番号：${esc(s.orderNumber)}</div></div><p class="customer">${esc(s.companyName)} 御中</p><p>${esc(s.contactName)} 様</p><p>発行者：${esc(issuer.name)}<br>${esc(issuer.address)}<br>${esc(issuer.email)}${issuer.registrationNumber?`<br>登録番号：${esc(issuer.registrationNumber)}`:''}</p>${content}<footer>発行時点の記録を保存した書面です。後の変更・返金は精算記録でご確認ください。印刷・PDF保存は補助機能です。</footer></main><script nonce="${nonce}">document.getElementById('print').addEventListener('click',()=>window.print())</script></body></html>`
}
