import 'server-only'
import { createHmac, timingSafeEqual, randomBytes } from 'node:crypto'
import { adminClient } from '@/lib/supabase/admin'
import { mailOrigin, uuid } from '@/lib/oem-mail-security'
import type { TrialPrepaymentInvoice } from './oem-trial-payments-shared'
function signature(id:string) { const secret=process.env.OEM_INTAKE_HASH_SECRET||process.env.SUPABASE_SERVICE_ROLE_KEY; if(!secret)throw new Error('Invoice link signing is not configured'); return createHmac('sha256',secret).update(`oem-trial-prepayment:v1:${id}`).digest('base64url') }
export function trialPrepaymentInvoiceUrl(id:string) { const value=uuid(id); return `${mailOrigin()}/btob/trial-invoice/${value}.${signature(value)}` }
export async function getTrialPrepaymentInvoiceForToken(token:string):Promise<TrialPrepaymentInvoice|null> { if(!/^[0-9a-f-]{36}\.[A-Za-z0-9_-]{43}$/.test(token))return null;const [id,sig]=token.split('.');try{uuid(id)}catch{return null};try{if(!timingSafeEqual(Buffer.from(signature(id)),Buffer.from(sig)))return null}catch{return null};const {data,error}=await adminClient.from('oem_trial_prepayment_invoices').select('*,oem_trial_prepayments!inner(status)').eq('id',id).eq('lifecycle_status','active').neq('oem_trial_prepayments.status','void').maybeSingle();return error||!data?null:data as TrialPrepaymentInvoice }
function esc(value:unknown){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!))}
export function trialPrepaymentInvoiceResponse(invoice:Pick<TrialPrepaymentInvoice,'invoice_number'|'snapshot'>,kind:'initial'|'additional'='initial'):Response { const s=invoice.snapshot;const nonce=randomBytes(18).toString('base64');const html=`<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive"><title>${kind==='additional'?'追加試作費請求書':'試作前払い請求書'} ${esc(invoice.invoice_number)}</title><style nonce="${nonce}">body{font-family:system-ui,sans-serif;color:#222;max-width:760px;margin:32px auto;padding:0 18px}header{display:flex;justify-content:space-between;border-bottom:2px solid #222;padding-bottom:16px}table{width:100%;border-collapse:collapse;margin-top:28px}th,td{border-bottom:1px solid #ddd;padding:12px;text-align:left}td:last-child,th:last-child{text-align:right}.total{font-size:1.25rem;font-weight:700}@media print{body{margin:0;padding:0}}@page{size:A4;margin:14mm}</style></head><body><header><h1>請求書</h1><div>請求書番号：${esc(invoice.invoice_number)}<br>発行日：${esc(s.issuedDate)}<br>支払期限：${esc(s.dueDate)}</div></header><p class="customer">${esc(s.companyName)} 御中<br>${esc(s.contactName)} 様</p><p>${esc(s.description)}</p><table><tr><th>項目</th><th>金額（税別）</th></tr><tr><td>${esc(s.description)}</td><td>¥${Number(s.taxableAmount).toLocaleString('ja-JP')}</td></tr><tr><td>消費税（10%）</td><td>¥${Number(s.taxAmount).toLocaleString('ja-JP')}</td></tr><tr class="total"><td>請求金額（税込）</td><td>¥${Number(s.grossAmount).toLocaleString('ja-JP')}</td></tr></table><p>${kind==='additional'?'追加試作1回分の費用です。':`${s.taxableAmount===5000 ? '初回特典は1企業（個人は1名）につき1回限り。' : '通常料金の試作契約です。'}試作2回までを含みます。追加試作は1回3,000円（税別）です。`}試作のみで終了でき、製造発注の義務はありません。製造へ進む場合は試作費を含まない製造請求（着手金・精算金）が別途発生します。<br>特殊食材：${esc(s.specialIngredientNote)}</p><p>発行者：${esc(s.issuer.name)}<br>${esc(s.issuer.address)}<br>${esc(s.issuer.email)}${s.issuer.registrationNumber ? `<br>適格請求書発行事業者登録番号：${esc(s.issuer.registrationNumber)}` : ''}<br>振込先：${esc(s.issuer.bankName)} ${esc(s.issuer.branchName)} ${esc(s.issuer.accountType)} ${esc(s.issuer.accountNumber)}<br>口座名義：${esc(s.issuer.accountHolder)}</p><p>${kind==='initial'?'全額の入金確認後に試作を開始します。':''}この書面は請求書です。領収書ではありません。お支払い済みの場合は行き違いの可能性があるため、担当者へご確認ください。</p></body></html>`;return new Response(html,{headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'private, no-store, max-age=0','X-Robots-Tag':'noindex, nofollow, noarchive','Referrer-Policy':'no-referrer','X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY', 'Content-Security-Policy':`default-src 'none'; style-src 'nonce-${nonce}'; base-uri 'none'; form-action 'none'`}}) }
export function unavailableTrialPrepaymentInvoice():Response{return new Response('請求書を表示できません。URLをご確認いただくか、担当者へお問い合わせください。',{status:404,headers:{'Content-Type':'text/plain; charset=utf-8','Cache-Control':'no-store','X-Robots-Tag':'noindex, nofollow'}})}
